# This file contains the configuration for all the applications.
common:
  # EFK Stack
  efk_namespace: "efk"
  efk_elasticsearch_name: "elasticsearch"
  efk_elasticsearch_version: "8.10.2"
  efk_elasticsearch_node_count: 1
  efk_kibana_name: "kibana"
  efk_kibana_version: "8.10.2"
  efk_kibana_node_count: 1

  # Traefik
  traefik_namespace: "traefik"
  traefik_values:
    providers:
      kubernetesCRD:
        enabled: true

dev:
  # Development-specific overrides
  # example:
  # efk_elasticsearch_node_count: 1

staging:
  # Staging-specific overrides
  # example:
  # efk_elasticsearch_node_count: 2

autopush:
  # Autopush-specific overrides
  # example:
  # efk_elasticsearch_node_count: 1

prod:
  # Production-specific overrides
  # example:
  # efk_elasticsearch_node_count: 3
