{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "puter.fullname" . }}
  labels:
    {{- include "puter.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.hosts }}`)
      kind: Rule
      services:
        - name: {{ include "puter.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: letsencrypt
{{- end }}
