- name: Create redis secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: redis-auth
        namespace: redis
      type: Opaque
      stringData:
        password: "{{ service_password }}"
