apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: coder-admin-creds
  namespace: coder
spec:
  vault:
    address: http://vault.vault:8200
    auth:
      kubernetes:
        mountPath: kubernetes
        role: homelab-role
  mount: secret
  path: homelab/coder/admin
  type: Opaque
  data:
    username: "user"
    password: "password"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: coder-db-creds
  namespace: coder
spec:
  vault:
    address: http://vault.vault:8200
    auth:
      kubernetes:
        mountPath: kubernetes
        role: homelab-role
  mount: secret
  path: homelab/coder/db
  type: Opaque
  data:
    password: "password"
