---
- name: Create rreading-glasses namespace
  kubernetes.core.k8s:
    name: "{{ rreading_glasses_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy rreading-glasses from helm chart
  kubernetes.core.helm:
    name: rreading-glasses
    chart_ref: "charts/{{ rreading_glasses_helm_chart }}"
    release_namespace: "{{ rreading_glasses_namespace }}"
    create_namespace: true
    values: "{{ lookup('file', 'config/apps/rreading-glasses/values.yaml') | from_yaml }}"
