- name: Set desired DHCP static list
  ansible.builtin.set_fact:
    desired_dhcp_staticlist: >-
      {{ asuswrt_dhcp_static_leases | map(attribute='mac') |
      zip(asuswrt_dhcp_static_leases | map(attribute='ip')) |
      zip(asuswrt_dhcp_static_leases | map(attribute='name')) |
      map('flatten') | map('join', '>') | join(' ') }}

- name: Manage DHCP static list
  community.general.nvram:
    name: dhcp_staticlist
    value: "{{ desired_dhcp_staticlist }}"
  notify: commit_nvram_changes
