---
- name: Include system configuration tasks
  include_tasks: system.yml

- name: Include Wi-Fi configuration tasks
  include_tasks: wifi.yml

- name: Include DHCP static lease tasks
  include_tasks: dhcp.yml

- name: Include Port Forwarding tasks
  include_tasks: port_forwarding.yml
