- name: Get current port forwarding list
  community.general.nvram:
    name: vts_rulelist
  register: vts_rulelist_raw
  changed_when: false
  check_mode: false

- name: Set desired port forwarding list
  ansible.builtin.set_fact:
    desired_vts_rulelist: >-
      {{ asuswrt_port_forwards | map(attribute='description') |
      zip(asuswrt_port_forwards | map(attribute='external_port')) |
      zip(asuswrt_port_forwards | map(attribute='internal_ip')) |
      zip(asuswrt_port_forwards | map(attribute='internal_port')) |
      zip(asuswrt_port_forwards | map(attribute='protocol')) |
      map('flatten') | map('join', '>') | join('<') }}

- name: Manage port forwarding list
  community.general.nvram:
    name: vts_rulelist
    value: "{{ desired_vts_rulelist }}"
  when: vts_rulelist_raw.value != desired_vts_rulelist
  notify: commit_nvram_changes
