---
- name: Set hostname
  community.general.nvram:
    name: odmpid
    value: "{{ odmpid }}"
  notify: commit_nvram_changes

- name: Set sshd enabled
  community.general.nvram:
    name: sshd_enable
    value: "1"
  notify: commit_nvram_changes

- name: Set sshd wan access
  community.general.nvram:
    name: sshd_wan
    value: "1"
  notify: commit_nvram_changes
