---
- name: Configure wifi settings
  community.general.nvram:
    name: "{{ item.nvram_prefix }}_ssid"
    value: "{{ item.ssid }}"
  loop: "{{ asuswrt_wifi_config }}"
  notify: restart_wireless

- name: Configure wifi password
  community.general.nvram:
    name: "{{ item.nvram_prefix }}_wpa_psk"
    value: "{{ item.password }}"
  loop: "{{ asuswrt_wifi_config }}"
  notify: restart_wireless

- name: Configure wifi channel
  community.general.nvram:
    name: "{{ item.nvram_prefix }}_channel"
    value: "{{ item.channel }}"
  loop: "{{ asuswrt_wifi_config }}"
  notify: restart_wireless
