---
- name: Create ArgoCD Namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-helm"
    state: present

- name: Deploy ArgoCD with Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    values: "{{ lookup('template', 'argocd-values.yml.j2') | from_yaml }}"

- name: Create ArgoCD IngressRoute
  kubernetes.core.k8s:
    state: present
    template: 'argocd-ingressroute.yml.j2'
