- name: Create Grafana LDAP secret
  kubernetes.core.k8s:
    state: present
    template:
      - path: grafana-ldap.toml.j2
        dest: /tmp/grafana-ldap.toml
    dest: "{{ grafana_ldap_secret_dest }}"
    namespace: monitoring
  vars:
    grafana_ldap_secret_dest: /tmp/grafana-ldap-secret.yml

- name: Create Traefik dashboard
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: traefik-dashboard
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
      data:
        traefik.json: "{{ lookup('template', 'traefik-dashboard.json.j2') }}"
