---
- name: Deploy Traefik
  ansible.builtin.include_tasks: traefik.yml

- name: Deploy Authelia
  ansible.builtin.include_tasks: authelia.yml

- name: Configure Grafana
  ansible.builtin.include_tasks: grafana.yml

- name: Deploy ArgoCD
  ansible.builtin.include_tasks: argocd.yml
