---
- name: Find all application values files
  find:
    paths: "{{ playbook_dir }}/../../config/apps"
    patterns: "values.yaml"
    recurse: yes
  register: values_files

- name: Debug values_files
  debug:
    var: values_files

- name: Create secrets from values files
  block:
    - name: Create secrets
      include_tasks: create_secrets.yml
      loop: "{{ values_files.files }}"
      loop_control:
        loop_var: values_file
  rescue:
    - name: Fail
      fail:
        msg: "Failed to create secrets for {{ values_file.path }}"
