[servers]
host = "openldap.ldap.svc.cluster.local"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "cn=admin,dc=homelab,dc=com"
bind_password = "<path:secret/data/openldap#admin-password>"
search_filter = "(uid=%s)"
search_base_dns = ["ou=users,dc=homelab,dc=com"]

[[servers.group_mappings]]
group_dn = "cn=homelab-admins,ou=groups,dc=homelab,dc=com"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=homelab-developers,ou=groups,dc=homelab,dc=com"
org_role = "Editor"
