- name: Test Synology module
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Synology module
      synology.nas.synology:
        host: "localhost"
        username: "admin"
        password: "password"
        resource: "user"
        name: "testuser"
        state: "present"
      ignore_errors: true
