---
# tasks file for minio

- name: Create minio group
  group:
    name: minio
    state: present

- name: Create minio user
  user:
    name: minio
    group: minio
    home: "{{ minio_data_dir }}"
    create_home: yes
    shell: /bin/bash

- name: Create data directory
  file:
    path: "{{ minio_data_dir }}"
    state: directory
    owner: minio
    group: minio
    mode: '0755'

- name: Download and install minio binary
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio.{{ minio_version }}"
    dest: /usr/local/bin/minio
    mode: '0755'
  notify: restart minio

- name: Create systemd service file
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: Start and enable minio service
  systemd:
    name: minio
    state: started
    enabled: yes
    daemon_reload: yes
