galaxy_info:
  author: Your Name
  description: Deploys the Vault Secrets Operator
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Generic
      versions:
        - all
  galaxy_tags: []

dependencies: []
