---
- name: Add HashiCorp Helm repository
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Create Vault namespace
  kubernetes.core.k8s:
    name: "{{ vault_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Vault Helm chart
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: "{{ vault_namespace }}"
    create_namespace: true
    values: "{{ vault_values }}"
