ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: authelia@kubernetescrd
    hosts:
      - host: "homepage.homelab.dev"
        paths:
          - path: /
            pathType: Prefix
