---
# tasks file for proxmox_host

- name: Update and upgrade apt packages
  apt:
    update_cache: true
    upgrade: dist
    autoremove: true
  register: apt_upgrade

- name: Reboot if required
  reboot:
    when: apt_upgrade.reboot_required
