---
# tasks file for proxmox_host storage configuration

- name: Configure LVM storage
  community.general.proxmox_storage:
    node: "{{ ansible_hostname }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    vgname: "{{ item.vgname }}"
    content: "images,rootdir"
  loop: "{{ proxmox_host_storage }}"
  when: item.type == 'lvm'

- name: Configure NFS storage
  community.general.proxmox_storage:
    node: "{{ ansible_hostname }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    server: "{{ item.server }}"
    path: "{{ item.path }}"
    options: "{{ item.options | default(omit) }}"
    content: "vztmpl,iso,backup"
  loop: "{{ proxmox_host_storage }}"
  when: item.type == 'nfs'

- name: Configure SMB storage
  community.general.proxmox_storage:
    node: "{{ ansible_hostname }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    server: "{{ item.server }}"
    share: "{{ item.share }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    content: "vztmpl,iso,backup"
  loop: "{{ proxmox_host_storage }}"
  when: item.type == 'smb'
