---
- name: Apply application manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "{{ playbook_dir }}/../../apps/*.yml"
  loop_control:
    loop_var: item
