---
- name: Deploy sabnzbd
  ansible.builtin.include_tasks: sabnzbd.yml

- name: Deploy sonarr
  ansible.builtin.include_tasks: sonarr.yml

- name: Deploy jellyfin
  ansible.builtin.include_tasks: jellyfin.yml

- name: Deploy jellyseerr
  ansible.builtin.include_tasks: jellyseerr.yml

- name: Deploy workadventure
  ansible.builtin.include_tasks: workadventure.yml

- name: Deploy apps
  ansible.builtin.template:
    src: apps.yml.j2
    dest: /tmp/apps.yml
  register: apps

- name: Apply apps
  kubernetes.core.k8s:
    state: present
    apply: yes
    src: /tmp/apps.yml
  when: apps.changed
