- name: Apply configmaps from templates
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', item) | from_yaml }}"
  with_items:
    - 'main.yml.j2'
    - 'all.yml.j2'
