- name: Download Consul
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/tmp/consul_{{ consul_version }}_linux_amd64.zip"
    mode: '0644'

- name: Unarchive Consul
  ansible.builtin.unarchive:
    src: "/tmp/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    creates: /usr/local/bin/consul

- name: Configure Consul
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    mode: '0644'

- name: Start Consul service
  ansible.builtin.systemd:
    name: consul
    state: started
    enabled: yes
