---
- name: Install dependencies
  apt:
    name:
      - git
      - build-essential
      - pve-headers
    state: present

- name: Clone QEMU anti-detection patch
  git:
    repo: https://github.com/zhaodice/qemu-anti-detection.git
    dest: /tmp/qemu-anti-detection

- name: Apply QEMU anti-detection patch
  shell: |
    cd /tmp/qemu-anti-detection
    ./install.sh
  args:
    creates: /usr/lib/x86_64-linux-gnu/pve-qemu-kvm/qemu-system-x86_64.bak

- name: Clone Proxmox VE anti-detection patch
  git:
    repo: https://github.com/zhaodice/proxmox-ve-anti-detection.git
    dest: /tmp/proxmox-ve-anti-detection

- name: Apply Proxmox VE anti-detection patch
  shell: |
    cd /tmp/proxmox-ve-anti-detection
    ./install.sh
  args:
    creates: /usr/share/pve-manager/js/pvemanagerlib.js.bak

- name: Restart pveproxy service
  service:
    name: pveproxy
    state: restarted
