---
all:
  hosts:
    proxmox:
      ansible_host: 192.168.1.100
      ansible_user: root

k3s_cluster:
  children:
    master:
      hosts:
        k3s-master-1:
          ansible_host: 192.168.1.101
    workers:
      hosts:
        k3s-worker-1:
          ansible_host: 192.168.1.102
        k3s-worker-2:
          ansible_host: 192.168.1.103
