name: ci
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install test dependencies.
        run: pip install ansible-lint
      - name: Run Ansible Lint.
        run: ansible-lint
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init -backend=false
      - name: Terraform Validate
        run: terraform -chdir=terraform validate
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init -backend=false
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: homelab-importer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/homelab-importer:latest
  trigger-argocd-sync:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Trigger Argo CD Sync
        uses: appleboy/argocd-sync-action@master
        with:
          server_url: ${{ secrets.ARGOCD_SERVER_URL }}
          auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          app_name: 'homelab-importer'
