---
- name: Create homepage namespace
  kubernetes.core.k8s:
    name: "{{ homepage_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy homepage from helm chart
  kubernetes.core.helm:
    name: homepage
    chart_ref: "{{ homepage_helm_chart }}"
    chart_repo_url: "{{ homepage_helm_repo }}"
    chart_version: "{{ homepage_helm_version }}"
    release_namespace: "{{ homepage_namespace }}"
    create_namespace: true
    values: "{{ lookup('file', 'config/apps/homepage/values.yaml') | from_yaml }}"
