---
- name: Install python3-venv
  ansible.builtin.package:
    name: python3-venv
    state: present

- name: Create virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/secure-gen
    creates: /opt/secure-gen/bin/activate

- name: Install python libraries
  ansible.builtin.pip:
    name:
      - hvac
      - cryptography
      - python-gnupg
    virtualenv: /opt/secure-gen

- name: Copy secure-gen tool
  ansible.builtin.copy:
    src: secure-gen
    dest: /opt/secure-gen/bin/secure-gen
    mode: '0755'
