apiVersion: v2
name: metube
description: A Helm chart for MeTube
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
- name: common
  version: "0.1.0"
  repository: "file://../common"
