---
- name: Generate k3s join token
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_point: "secret"
    path: "k3s"
    data:
      join_token: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
  register: k3s_join_token_result
  until: k3s_join_token_result is success
  retries: 5
  delay: 2
