---
- name: Create faster-whisper namespace
  kubernetes.core.k8s:
    name: "{{ faster_whisper_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy faster-whisper from helm chart
  kubernetes.core.helm:
    name: faster-whisper
    chart_ref: "charts/{{ faster_whisper_helm_chart }}"
    release_namespace: "{{ faster_whisper_namespace }}"
    create_namespace: true
    values: "{{ lookup('file', 'config/apps/faster-whisper/values.yaml') | from_yaml }}"
