---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
    image: "bflad/kind-action:v1.2.0"
    command: ""
    pull: true
    privileged: true
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
    security_opts:
      - "seccomp=unconfined"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles"
  playbooks:
    converge: ../../../../playbooks/setup.yml
verifier:
  name: ansible
  enabled: false
