apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: gitea-admin-creds
  namespace: gitea
spec:
  vault:
    address: http://vault.vault:8200
    auth:
      kubernetes:
        mountPath: kubernetes
        role: homelab-role
  mount: secret
  path: homelab/gitea/admin
  type: Opaque
  data:
    username: "user"
    password: "password"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: gitea-db-creds
  namespace: gitea
spec:
  vault:
    address: http://vault.vault:8200
    auth:
      kubernetes:
        mountPath: kubernetes
        role: homelab-role
  mount: secret
  path: homelab/gitea/db
  type: Opaque
  data:
    password: "password"
