apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metube.fullname" . }}
  labels:
    {{- include "metube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metube.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.downloads.enabled }}
            - name: downloads
              mountPath: {{ .Values.persistence.downloads.mountPath }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.downloads.enabled }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ include "metube.fullname" . }}-downloads
        {{- end }}
