{{- if .Values.persistence.downloads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metube.fullname" . }}-downloads
  labels:
    {{- include "metube.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size | quote }}
  {{- if .Values.persistence.downloads.storageClass }}
  storageClassName: {{ .Values.persistence.downloads.storageClass | quote }}
  {{- end }}
{{- end }}
