- name: Commit NVRAM changes
  ansible.builtin.raw: nvram commit
  changed_when: false
  listen: "commit_nvram_changes"

- name: Restart wireless service
  ansible.builtin.raw: service restart_wireless
  changed_when: false
  listen: "restart_wireless"
