apiVersion: v1
kind: Service
metadata:
  name: {{ include "bolt.fullname" . }}
  labels:
    {{- include "bolt.labels" . | nindent 4 }}
    traefik.enable: "true"
    traefik.http.routers.bolt.rule: "Host(`{{ .Values.ingress.hosts }}`)"
    traefik.http.routers.bolt.entrypoints: "websecure"
    traefik.http.routers.bolt.tls.certresolver: "letsencrypt"
    traefik.http.services.bolt.loadbalancer.server.port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bolt.selectorLabels" . | nindent 4 }}
