---
# This is the main configuration file for the homelab.
# It contains all the settings that are not specific to a single application.

# Domain settings
# These settings are used to configure the domain name and subdomains for the homelab.
domain_name: "example.com"
apps_subdomain: "apps"

# User settings
# These settings are used to configure the default admin user.
admin_user: "admin"

# IP settings
# These settings are used to configure the IP addresses for the homelab.
k3s_vip: "192.168.1.110"
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
proxmox_host_ip: "192.168.1.100"
proxmox_host_netmask: "255.255.255.0"
proxmox_host_gateway: "192.168.1.1"

# Proxmox settings
# These settings are used to configure the Proxmox hypervisor.
proxmox_node: "pve"
proxmox_storage: "local-lvm"
proxmox_bridge: "vmbr0"
pm_api_url: "https://192.168.1.100:8006/api2/json"

# K3s settings
# These settings are used to configure the K3s cluster.
k3s_version: "v1.24.4+k3s1"
k3s_master_count: 1
k3s_worker_count: 2
k3s_vm_memory: 2048
k3s_vm_cores: 2
k3s_vm_disk_size: "20G"
k3s_master_prefix: "k3s-master"
k3s_worker_prefix: "k3s-worker"

# VM template settings
# These settings are used to configure the VM template.
template_name: "ubuntu-2204-cloud-init"
template_vmid: 9000
os_image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"

# Network settings
# These settings are used to configure the network.
network_vlan_tag: -1
network_cidr: "192.168.1.0/24"
