---
- name: Setup Homelab
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: homelab-config
    - role: k3s-cluster
    - role: traefik
    - role: efk-stack
    - role: core_services
    - role: applications
    - role: mealie
    - role: n8n
    - role: stirling-pdf
