- name: Generate secrets
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run secure_gen script
      ansible.builtin.command: "python3 {{ secure_gen_role_path }}/files/secure-gen --config-file ../../../../private/config.yml"
      register: secure_gen_result
      changed_when: secure_gen_result.rc != 0
      args:
        chdir: "{{ secure_gen_role_path }}/files"
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
        VAULT_TOKEN: "{{ vault_token }}"
      vars:
        secure_gen_role_path: "{{ 'ansible/roles/secure_gen' | realpath }}"
