---
- name: Generate secrets
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run secure-gen script
      command: "python3 {{ role_path }}/files/secure-gen"
      args:
        chdir: "{{ role_path }}/files"
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
        VAULT_TOKEN: "{{ vault_token }}"
      vars:
        role_path: "{{ 'ansible/roles/secure-gen' | realpath }}"
