---
- name: Setup K3s Cluster
  hosts: k3s_masters:k3s_workers
  roles:
    - role: k3s_cluster

- name: Setup Homelab
  hosts: k3s_masters
  roles:
    - role: homelab
    - vault
    - vault_secrets
    - openldap
    - role: efk_stack
    - role: velero
    - role: homepage
    - role: redis

- name: Setup pfSense
  hosts: pfsense
  roles:
    - role: pfsense
