---
- name: Setup K3s Cluster
  hosts: k3s_masters:k3s_workers
  roles:
    - role: k3s_cluster

- name: Setup Core Infrastructure
  hosts: k3s_masters
  roles:
    - core_infra
    - vault

- name: Setup Core Applications
  hosts: k3s_masters
  roles:
    - core_apps
    - openldap
    - role: efk_stack
