---
- name: Test Synology Module
  hosts: localhost
  gather_facts: false
  collections:
    - synology.nas
  vars:
    ansible_host: "mock-synology-api"
    ansible_port: 8000
    ansible_user: "admin"
    ansible_password: "password" # This is a mock password, not a real one
    test_user: "testuser"
    test_group: "testgroup"
    test_folder: "testfolder"

  tasks:
    - name: Create test user
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: user
        name: "{{ test_user }}"
        state: present
        config:
          email: "testuser@example.com"
          password: "some_password"
      register: create_user_result

    - name: Verify user creation
      assert:
        that:
          - create_user_result.changed

    - name: Create test user again (idempotency check)
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: user
        name: "{{ test_user }}"
        state: present
        config:
          email: "testuser@example.com"
          password: "some_password"
      register: create_user_idempotent_result

    - name: Verify user creation idempotency
      assert:
        that:
          - not create_user_idempotent_result.changed

    - name: Delete test user
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: user
        name: "{{ test_user }}"
        state: absent
      register: delete_user_result

    - name: Verify user deletion
      assert:
        that:
          - delete_user_result.changed

    - name: Create test group
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: group
        name: "{{ test_group }}"
        state: present
        config:
          description: "Test group"
      register: create_group_result

    - name: Verify group creation
      assert:
        that:
          - create_group_result.changed

    - name: Delete test group
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: group
        name: "{{ test_group }}"
        state: absent
      register: delete_group_result

    - name: Verify group deletion
      assert:
        that:
          - delete_group_result.changed

    - name: Create test shared folder
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: shared_folder
        name: "{{ test_folder }}"
        state: present
      register: create_folder_result

    - name: Verify folder creation
      assert:
        that:
          - create_folder_result.changed

    - name: Delete test shared folder
      synology.nas.synology:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        use_ssl: false
        resource: shared_folder
        name: "{{ test_folder }}"
        state: absent
      register: delete_folder_result

    - name: Verify folder deletion
      assert:
        that:
          - delete_folder_result.changed
