apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  vault:
    address: http://vault.vault:8200
    auth:
      kubernetes:
        mountPath: kubernetes
        role: homelab-role
  mount: secret
  path: homelab/grafana/admin
  type: Opaque
  data:
    password: "password"
