# Default values for homebox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sysadminsmedia/homebox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 7745

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: homebox.local
      paths:
        - path: /
          pathType: ImplementationSpecific

persistence:
  enabled: false
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: ""
