- name: Create vmbr2 bridge
  community.general.proxmox_bridge:
    node: "{{ proxmox_host }}"
    bridge: vmbr2
    comment: "Service Network"

- name: Create VLAN 10 on vmbr2
  community.general.proxmox_vlan:
    node: "{{ proxmox_host }}"
    vlan: 10
    bridge: vmbr2
    comment: "VLAN 10 for services"
