- name: Install ECK CRDs
  k8s:
    src: https://download.elastic.co/downloads/eck/3.0.0/crds.yaml
    state: present

- name: Install ECK Operator
  k8s:
    src: https://download.elastic.co/downloads/eck/3.0.0/operator.yaml
    state: present

- name: Create Elasticsearch cluster
  k8s:
    template: elasticsearch.yml.j2
    state: present

- name: Create Kibana instance
  k8s:
    template: kibana.yml.j2
    state: present

- name: Create Fluentd DaemonSet
  k8s:
    template: fluentd.yml.j2
    state: present
