---
- name: Deploy Traefik
  ansible.builtin.include_tasks: traefik.yml

- name: Deploy Authelia
  ansible.builtin.include_tasks: authelia.yml

- name: Configure Grafana
  ansible.builtin.include_tasks: grafana.yml

- name: Deploy ArgoCD
  include_tasks: argocd.yml

- name: Deploy apps
  template:
    src: apps.yml.j2
    dest: /tmp/apps.yml
  register: apps

- name: Apply apps
  shell: kubectl apply -f /tmp/apps.yml
  when: apps.changed

- name: Deploy sabnzbd
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/../../../apps/sabnzbd.yml"

- name: Deploy MinIO ServiceMonitor
  k8s:
    template: minio-servicemonitor.yml.j2
    state: present
