---
- name: Deploy Traefik
  ansible.builtin.include_tasks: traefik.yml

- name: Deploy Authelia
  ansible.builtin.include_tasks: authelia.yml

- name: Configure Grafana
  ansible.builtin.include_tasks: grafana.yml

- name: Deploy ArgoCD
  include_tasks: argocd.yml

- name: Deploy apps
  template:
    src: apps.yml.j2
    dest: /tmp/apps.yml
  register: apps

- name: Apply apps
  shell: kubectl apply -f /tmp/apps.yml
  when: apps.changed

- name: Deploy sabnzbd
  ansible.builtin.include_tasks: sabnzbd.yml

- name: Deploy sonarr
  ansible.builtin.include_tasks: sonarr.yml

- name: Deploy jellyfin
  ansible.builtin.include_tasks: jellyfin.yml

- name: Deploy jellyseerr
  ansible.builtin.include_tasks: jellyseerr.yml

- name: Deploy workadventure
  ansible.builtin.include_tasks: workadventure.yml

- name: Deploy MinIO ServiceMonitor
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'minio-servicemonitor.yml.j2') | from_yaml }}"
