---
- name: "Add Traefik Helm repository"
  kubernetes.core.helm_repository:
    name: "traefik"
    repo_url: "{{ traefik_helm_repo_url }}"

- name: "Create Traefik namespace"
  kubernetes.core.k8s:
    name: "{{ traefik_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Deploy Traefik Helm chart"
  kubernetes.core.helm:
    name: "traefik"
    chart_ref: "traefik/traefik"
    release_namespace: "{{ traefik_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'traefik-values.yml.j2') | from_yaml }}"
