- name: Setup K3s Cluster
  hosts: k3s_masters:k3s_workers
  roles:
    - role: k3s_cluster

- name: Configure Vault
  hosts: localhost
  connection: local
  roles:
    - role: vault-pki
    - role: vault-secrets-operator
