---
- name: Setup Core Services
  hosts: k3s_masters
  roles:
    - role: homelab
    - vault
    - vault-secrets-operator
    - openldap
    - role: efk-stack
    - role: velero
    - role: homepage
    - role: redis

- name: Setup pfSense
  hosts: pfsense
  roles:
    - role: pfsense
