---
- name: Create Monitoring Namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Add Prometheus Community Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
    state: present

- name: Deploy Kube Prometheus Stack with Helm
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    values: "{{ lookup('template', 'monitoring-values.yml.j2') | from_yaml }}"

- name: Create Grafana IngressRoute
  kubernetes.core.k8s:
    state: present
    template: 'grafana-ingressroute.yml.j2'
