---
- name: Create Pi-hole Namespace
  kubernetes.core.k8s:
    name: pihole
    api_version: v1
    kind: Namespace
    state: present

- name: Add Pi-hole Helm repository
  kubernetes.core.helm_repository:
    name: mojo2600
    repo_url: "https://mojo2600.github.io/pihole-kubernetes/"
    state: present

- name: Deploy Pi-hole with Helm
  kubernetes.core.helm:
    name: pihole
    chart_ref: mojo2600/pihole
    release_namespace: pihole
    values: "{{ lookup('template', 'pihole-values.yml.j2') | from_yaml }}"

- name: Create Pi-hole IngressRoute
  kubernetes.core.k8s:
    state: present
    template: 'pihole-ingressroute.yml.j2'
