---
# tasks file for velero

- name: Fetch MinIO credentials from Vault
  community.hashi_vault.vault_kv2_get:
    path: "{{ velero_vault_path }}"
  register: minio_credentials

- name: Create the velero directory
  file:
    path: "{{ velero_install_dir }}"
    state: directory
    mode: '0755'

- name: Download and unarchive the Velero client
  unarchive:
    src: "https://github.com/vmware-tanzu/velero/releases/download/v{{ velero_version }}/velero-v{{ velero_version }}-linux-amd64.tar.gz"
    dest: "{{ velero_install_dir }}"
    remote_src: yes
    creates: "{{ velero_install_dir }}/velero"

- name: Move velero binary to /usr/local/bin
  copy:
    src: "{{ velero_install_dir }}/velero-v{{ velero_version }}-linux-amd64/velero"
    dest: /usr/local/bin/velero
    mode: '0755'
    remote_src: yes
  notify: restart velero

- name: Create Velero secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: velero-minio-creds
        namespace: velero
      stringData:
        cloud: |
          [default]
          aws_access_key_id={{ minio_credentials.data[velero_vault_access_key_name] }}
          aws_secret_access_key={{ minio_credentials.data[velero_vault_secret_key_name] }}

- name: Install velero
  command: >
    velero install \
      --provider aws \
      --plugins velero/velero-plugin-for-aws:v1.5.0 \
      --bucket velero \
      --secret-file velero-minio-creds \
      --use-restic \
      --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.minio.svc:9000

- name: Create velero schedule
  template:
    src: schedule.yml.j2
    dest: "{{ velero_install_dir }}/schedule.yml"

- name: Apply velero schedule
  command: "kubectl apply -f {{ velero_install_dir }}/schedule.yml"
  changed_when: true
