# tasks file for velero

- name: Create the velero directory
  ansible.builtin.file:
    path: "{{ velero_install_dir }}"
    state: directory
    mode: '0755'

- name: Download and unarchive the Velero client
  ansible.builtin.unarchive:
    src: >-
      https://github.com/vmware-tanzu/velero/releases/download/v{{ velero_version }}/velero-v{{
      velero_version }}-linux-amd64.tar.gz
    dest: "{{ velero_install_dir }}"
    remote_src: true
    creates: "{{ velero_install_dir }}/velero"

- name: Move velero binary to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ velero_install_dir }}/velero-v{{ velero_version }}-linux-amd64/velero"
    dest: /usr/local/bin/velero
    mode: '0755'
    remote_src: true
  notify: restart velero

- name: Get Minio credentials from vault
  ansible.builtin.set_fact:
    velero_minio_credentials: "{{ lookup('community.hashi_vault.vault_kv2_get', velero_minio_vault_path, engine_mount_point='secret') }}"
  no_log: true

- name: Create Velero secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: velero-minio-creds
        namespace: velero
      stringData:
        cloud: |
          [default]
          aws_access_key_id={{ velero_minio_credentials[velero_minio_vault_access_key_name] }}
          aws_secret_access_key={{ velero_minio_credentials[velero_minio_vault_secret_key_name] }}

- name: Install Velero using Helm chart
  kubernetes.core.helm:
    name: velero
    chart_ref: velero
    chart_repo_url: https://vmware-tanzu.github.io/helm-charts
    release_namespace: velero
    create_namespace: true
    values:
      configuration:
        provider: aws
        backupStorageLocation:
          name: default
          bucket: velero
          config:
            region: minio
            s3ForcePathStyle: "true"
            s3Url: "http://minio.minio.svc:9000"
      credentials:
        useSecret: true
        secretName: velero-minio-creds
      deployRestic: true
      initContainers:
        - name: velero-plugin-for-aws
          image: "velero/velero-plugin-for-aws:v1.5.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins

- name: Create velero schedule
  ansible.builtin.template:
    src: schedule.yml.j2
    dest: "{{ velero_install_dir }}/schedule.yml"
    mode: '0644'

- name: Apply velero schedule
  kubernetes.core.k8s:
    state: present
    src: "{{ velero_install_dir }}/schedule.yml"
