---
# tasks file for velero

- name: Create the velero directory
  file:
    path: "{{ velero_install_dir }}"
    state: directory
    mode: '0755'

- name: Download and unarchive the Velero client
  unarchive:
    src: "https://github.com/vmware-tanzu/velero/releases/download/v{{ velero_version }}/velero-v{{ velero_version }}-linux-amd64.tar.gz"
    dest: "{{ velero_install_dir }}"
    remote_src: yes
    creates: "{{ velero_install_dir }}/velero"

- name: Move velero binary to /usr/local/bin
  copy:
    src: "{{ velero_install_dir }}/velero-v{{ velero_version }}-linux-amd64/velero"
    dest: /usr/local/bin/velero
    mode: '0755'
    remote_src: yes
  notify: restart velero

- name: Create velero credentials file for minio
  template:
    src: minio-credentials.j2
    dest: "{{ velero_install_dir }}/minio-credentials"

- name: Install velero
  command: >
    velero install \
      --provider aws \
      --plugins velero/velero-plugin-for-aws:v1.5.0 \
      --bucket velero \
      --secret-file {{ velero_install_dir }}/minio-credentials \
      --use-restic \
      --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.minio.svc:9000
  args:
    creates: /usr/local/bin/velero
