namespace: synology
name: nas
version: 1.0.0
readme: README.md
authors:
  - Your Name <your.email@example.com>
description: A collection to manage Synology NAS devices.
license:
  - GPL-2.0-or-later
tags:
  - synology
  - nas
  - storage
dependencies: {}
repository: http://example.com/repository
documentation: http://example.com/documentation
homepage: http://example.com/homepage
issues: http://example.com/issues
