apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appflowy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/toxicoder/homelabeazy.git'
    path: charts/appflowy
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: appflowy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
