apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "authelia"
  namespace: "argocd"
spec:
  project: "default"
  source:
    repoURL: "https://charts.authelia.com"
    chart: "authelia"
    targetRevision: "0.8.70"
    helm:
      valueFiles:
        - "config/apps/authelia/values.yaml"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "authelia"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
