apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.authelia.com'
    chart: authelia
    targetRevision: 0.8.70
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: auth.homelab.dev
          paths:
            - path: /
              pathType: Prefix

        pod:
          extraEnv:
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /etc/authelia/secrets/jwt_secret
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /etc/authelia/secrets/session_secret
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /etc/authelia/secrets/storage_encryption_key
          extraVolumes:
            - name: authelia-secrets
              secret:
                secretName: authelia-secrets
          extraVolumeMounts:
            - name: authelia-secrets
              mountPath: /etc/authelia/secrets
              readOnly: true

        authelia:
          jwt_secret: "" # This will be loaded from the secret
          default_redirection_url: https://homepage.homelab.dev
          authentication_backend:
            ldap:
              url: 'ldap://openldap.openldap.svc.cluster.local:389'
              base_dn: dc=homelab,dc=com
              username_attribute: uid
              additional_users_dn: ou=users
              users_filter: (&(objectClass=inetOrgPerson)(uid={username}))
              additional_groups_dn: ou=groups
              groups_filter: (member={dn})
              group_name_attribute: cn
              mail_attribute: mail
              display_name_attribute: displayName
              user: cn=admin,dc=homelab,dc=com
              password: "" # This will be loaded from the secret
          access_control:
            default_policy: deny
            rules:
              - domain: "*.homelab.dev"
                policy: bypass
          session:
            name: authelia_session
            secret: "" # This will be loaded from the secret
            expiration: 1h
            inactivity: 5m
          storage:
            encryption_key: "" # This will be loaded from the secret
            local:
              path: /var/lib/authelia/db.sqlite3
          notifier:
            filesystem:
              filename: /tmp/authelia/notification.txt

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
