apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.coder.com'
    chart: coder
    targetRevision: 0.22.0
    helm:
      values: |
        coder:
          admin:
            existingSecret: coder-admin-creds
          postgres:
            enabled: false
          database:
            type: mysql
            host: mariadb.mariadb.svc.cluster.local
            user: coder
            passwordSecret: "vault:secret/data/coder#db_creds"
            name: coder
          ldap:
            enabled: true
            url: "ldap://openldap.ldap.svc.cluster.local:389"
            bindDN: "cn=admin,dc=homelab,dc=com"
            bindPassword: "<vault:secret/data/openldap#admin-password>"
            userSearch:
              baseDN: "ou=users,dc=homelab,dc=com"
              filter: "(uid=%s)"
              username: "uid"
              email: "mail"
              name: "displayName"
            groupSearch:
              baseDN: "ou=groups,dc=homelab,dc=com"
              filter: "(member=%s)"
              name: "cn"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: coder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
