apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "gitea"
  namespace: "argocd"
spec:
  project: "default"
  source:
    repoURL: "https://dl.gitea.io/charts/"
    chart: "gitea"
    targetRevision: "9.0.0"
    helm:
      valueFiles:
        - "config/apps/gitea/values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "gitea"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
