apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 6.50.0
    helm:
      values: |
        adminPassword: <vault:secret/data/grafana#admin-password>
        persistence:
          enabled: true
          storageClassName: "longhorn"
          size: 10Gi
        ingressRoute:
          enabled: true
          entryPoints:
            - websecure
          routes:
            - match: Host(`grafana.homelab.dev`)
              kind: Rule
              services:
                - name: grafana
                  port: 3000
        metadata:
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: authelia@kubernetescrd
        service:
          type: ClusterIP
          port: 3000
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
