apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guacamole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmgrimes/homelab-apps.git'
    path: charts/guacamole
    targetRevision: HEAD
    helm:
      valueFiles:
        - "config/apps/guacamole/values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guacamole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
