apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/toxicoder/homelabeazy.git'
    path: charts/homebox
    targetRevision: HEAD
    helm:
      valueFiles:
        - "values.yaml"
        - "private/apps/homebox/values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homebox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
