apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'oci://ghcr.io/fallenbagel/jellyseerr'
    chart: 'jellyseerr-chart'
    targetRevision: '2.6.1'
    helm:
      values: |
        image:
          tag: "2.7.1"

        ingress:
          enabled: true
          hosts:
            - host: "jellyseerr.{{ domain_root }}"
              paths:
                - path: /
                  pathType: ImplementationSpecific

        config:
          persistence:
            size: 1Gi
            accessModes:
              - ReadWriteOnce

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jellyseerr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
