apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kasmtech/kasm-helm'
    chart: 'kasm-single-zone'
    targetRevision: 'release/1.17.0'
    helm:
      values: |
        global:
          hostname: "kasm.homelab.dev"
          altHostnames:
            - "*.kasm.homelab.dev"
        ldap:
          enabled: true
          host: "openldap.ldap.svc.cluster.local"
          port: 389
          bindDN: "cn=admin,dc=homelab,dc=com"
          bindPassword: "<path:secrets/data/openldap#admin-password>"
          userSearchBase: "ou=users,dc=homelab,dc=com"
          userSearchFilter: "(&(objectClass=inetOrgPerson)(uid=%s))"
          groupSearchBase: "ou=groups,dc=homelab,dc=com"
          groupSearchFilter: "(member=%s)"
          groupNameAttribute: "cn"
          userNameAttribute: "uid"
          userEmailAttribute: "mail"
          userFirstNameAttribute: "givenName"
          userLastNameAttribute: "sn"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kasm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
