apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mariadb
    targetRevision: 21.0.3
    helm:
      values: |
        auth:
          rootPassword: <path:secrets/data/mariadb#root-password>
          database: "gitea"
          username: "gitea"
          password: <path:secrets/data/gitea#db_creds>
        primary:
          persistence:
            enabled: true
            storageClass: "longhorn"
            size: 8Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
