apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meilisearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://meilisearch.github.io/meilisearch-kubernetes'
    chart: meilisearch
    targetRevision: 0.10.1
    helm:
      values: |
        meilisearch:
          masterKey: "<vault:secret/data/meilisearch#key>"
        persistence:
          enabled: true
          size: 5Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: meilisearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
