apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexta69/homelab
    path: charts/metube
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
