apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 45.28.0
    helm:
      values: |
        grafana:
          adminPassword: <vault:secret/data/grafana#admin-password>
          grafana.ini:
            auth.ldap:
              enabled: true
              config_file: /etc/grafana/ldap.toml
              allow_sign_up: true
          ldap:
            enabled: true
            config: |
              [servers]
              host = "openldap.ldap.svc.cluster.local"
              port = 389
              use_ssl = false
              start_tls = false
              ssl_skip_verify = true
              bind_dn = "cn=admin,dc=homelab,dc=com"
              bind_password = "<vault:secret/data/openldap#admin-password>"
              search_filter = "(uid=%s)"
              search_base_dns = ["ou=users,dc=homelab,dc=com"]

              [[servers.group_mappings]]
              group_dn = "cn=homelab-admins,ou=groups,dc=homelab,dc=com"
              org_role = "Admin"

              [[servers.group_mappings]]
              group_dn = "cn=homelab-developers,ou=groups,dc=homelab,dc=com"
              org_role = "Editor"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
