apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.otwld.com/'
    chart: ollama
    targetRevision: 1.25.0
    helm:
      valueFiles:
        - "config/apps/ollama/values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
