apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://open-webui.github.io/helm-charts'
    chart: open-webui
    targetRevision: 0.1.21 # Using a specific version is better practice
    helm:
      valueFiles:
        - "private/apps/open-webui/values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
