apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perplexica
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/toxicoder/homelabeazy.git'
    path: charts/perplexica
    targetRevision: HEAD
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: authelia@kubernetescrd
          hosts:
            - host: "perplexica.{{ domain_root }}"
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: perplexica
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
