apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pi-hole/docker-pi-hole.git
    targetRevision: '2025.07.1'
    path: '.'
    directory:
      recurse: true
    helm:
      values: |
        adminPassword: <path:secrets/data/pihole#admin-password>
        persistence:
          enabled: true
          storageClassName: "local-path"
          size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
