apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://portainer.github.io/k8s/'
    chart: portainer
    targetRevision: 2.27.9
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
          hosts:
            - host: portainer.homelab.dev
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
