apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: puter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HeyPuter/puter.git'
    path: charts/puter
    targetRevision: v2.5.1
    helm:
      values: |
        ingressRoute:
          enabled: true
          entryPoints:
            - websecure
          routes:
            - match: Host(`puter.local`)
              kind: Rule
              services:
                - name: puter
                  port: 4100
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
