apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rreading-glasses
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmgrimes/homelab-apps.git'
    path: charts/rreading-glasses
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rreading-glasses
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
