apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jules-Recruiter/homelab-SRE-challenge' # This will be replaced by the actual repo URL
    path: charts/vpn-app
    targetRevision: HEAD
    helm:
      values: |
        application:
          image:
            repository: "linuxserver/sabnzbd"
            tag: "latest"
          name: "sabnzbd"
          port: 8080

        gluetun:
          vpn:
            type: "openvpn"
            provider: "private internet access"
            region: "ca montreal"
            credentials:
              user: "YOUR_PIA_USERNAME"
              password: "YOUR_PIA_PASSWORD"

        service:
          type: ClusterIP
          port: 8080

        ingressRoute:
          enabled: true
          entryPoints:
            - websecure
          routes:
            - match: Host(`sabnzbd.your-domain.com`)
              kind: Rule
              services:
                - name: sabnzbd
                  port: 8080
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sabnzbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
