apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://searxng.github.io/searxng-helm-chart'
    chart: searxng
    targetRevision: 1.0.1
    helm:
      values: |
        ingressRoute:
          enabled: true
          entryPoints:
            - websecure
          routes:
            - match: Host(`searxng.homelab.dev`)
              kind: Rule
              services:
                - name: searxng
                  port: 8080
        searxng:
          settings:
            server:
              secret_key: "{{ .Values.searxng.secretkey }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: searxng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
