apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://searxng.github.io/searxng-helm-chart'
    chart: searxng
    targetRevision: 1.0.1
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - host: "searxng.homelab.dev"
              paths:
                - path: /
                  pathType: ImplementationSpecific
        searxng:
          settings:
            server:
              secret_key: "{{ .Values.searxng.secretkey }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: searxng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
