apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bjw-s.github.io/helm-charts'
    chart: sonarr
    targetRevision: 15.0.1
    helm:
      values: |
        image:
          repository: "linuxserver/sonarr"
          tag: "latest"

        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: authelia@kubernetescrd
            hosts:
              - host: "sonarr.{{ domain_root }}"
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sonarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
