apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jules-labs/jules-project' # Please replace with the correct git repo URL
    path: charts/stirling-pdf
    targetRevision: HEAD
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: authelia@kubernetescrd
          hosts:
            - host: "stirling-pdf.homelab.dev"
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          enabled: true
          size: 5Gi
          storageClass: "local-path"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
