apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://pkgs.tailscale.com/helmcharts'
    chart: tailscale-operator
    targetRevision: 1.84.3
    helm:
      values: |
        operator:
          apiSecret:
            secretName: tailscale-api-creds
            secretKey: apiKey
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
