apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: v25.0.0
    helm:
      values: |
        deployment:
          kind: DaemonSet
        service:
          spec:
            loadBalancerIP: 192.168.1.250
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: true
        globalArguments:
          - "--global.checknewversion"
          - "--global.sendanonymoususage"
        logs:
          general:
            level: INFO
          access:
            enabled: true
        ports:
          web:
            port: 80
            expose: true
            exposedPort: 80
          websecure:
            port: 443
            expose: true
            exposedPort: 443
            tls:
              enabled: true
        tls:
          options:
            default:
              minVersion: VersionTLS12
              cipherSuites:
                - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
                - TLS_AES_256_GCM_SHA384
                - TLS_CHACHA20_POLY1305_SHA256
        volumes:
          - name: main-config
            mountPath: /config
            configMap:
              name: main-config
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
