apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jules-Recruiter/homelab-SRE-challenge'
    path: charts/wireguard
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
