apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://geek-cookbook.github.io/charts/'
    chart: wg-easy
    targetRevision: 3.2.1
    helm:
      values: |
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: authelia@kubernetescrd
            hosts:
              - host: "wg.{{ domain_root }}"
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
