---
# Defaults for Traefik
traefik_namespace: traefik
traefik_values:
  ingressRoute:
    dashboard:
      enabled: true
  providers:
    kubernetesCRD:
      enabled: true
  # Additional middleware for Authelia
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia.authelia.svc.cluster.local/api/verify?rd=https://authelia.example.com/
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"

# Defaults for Authelia
authelia_namespace: authelia
authelia_values:
  ingress:
    enabled: true
    hosts:
      - host: authelia.example.com
        paths:
          - path: /
            pathType: Prefix

  # Configuration for users and OIDC clients
  authelia:
    access_control:
      default_policy: "two_factor"
      rules:
        - domain: "authelia.example.com"
          policy: "bypass"
    identity_providers:
      ldap:
        address: "ldap://openldap.default.svc.cluster.local"
        implementation: "custom"
        timeout: "5s"
        base_dn: "dc=example,dc=com"
        users_filter: "(&({search_filter})(objectClass=inetOrgPerson))"
        attributes:
          username: "uid"
          group_name: "cn"
          mail: "mail"
          display_name: "displayName"
        user: "cn=admin,dc=example,dc=com"
        password: "{{ lookup('community.hashi_vault.vault_read', 'secret/homelab/openldap/admin') }}" # This may need to be adjusted
    oidc:
      clients:
        - id: "my-app"
          secret: "{{ lookup('community.hashi_vault.vault_read', 'secret/homelab/authelia/oidc_client_secret') }}"
          redirect_uris:
            - "https://my-app.example.com/oauth2/callback"

# Defaults for Vault
vault_namespace: vault
vault_values:
  ui:
    enabled: true

  # High availability configuration
  ha:
    enabled: true
    replicas: 3

  # Persistent storage configuration
  # Replace with your desired storage class
  storage:
    size: 10Gi
    storageClass: "longhorn"
