apiVersion: v2
name: vpn-app
description: A Helm chart for deploying an application behind a VPN
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
