# The Site Configuration

# Import the theme
theme: just-the-docs

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Homelabeazy Documentation # the main title

tagline: "Your Homelab as Code" # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  "Your Homelab as Code"

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://toxicoder.github.io"
baseurl: "/homelabeazy"

github:
  username: toxicoder # change to your GitHub username

# Search settings
search_enabled: true

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# boolean type, the global switch for TOC in posts.
toc: true

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    line_numbers: true
    start_line: 1

defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"

# Just the Docs settings
nav_enabled: true
nav_sort: case_sensitive
nav_external_links:
  - title: Homelabeazy on GitHub
    url: https://github.com/toxicoder/homelabeazy

# Set the base color scheme to dark (will be overridden by custom SCSS)
color_scheme: dark

# Define custom callouts for different alert types
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
aux_links:
  "Homelabeazy on GitHub":
    - "https://github.com/toxicoder/homelabeazy"
