title: Homelabeazy Documentation
description: "Your Homelab as Code"
url: "https://toxicoder.github.io"
baseurl: "/homelabeazy"
logo: "/assets/logo.png"

# Build settings
remote_theme: just-the-docs/just-the-docs

permalink: pretty
