---
- name: Download k3s install script
  get_url:
    url: "https://get.k3s.io"
    dest: "/tmp/k3s-install.sh"
    mode: '0755'
  delegate_to: "{{ item }}"

- name: Install k3s server
  command: "/tmp/k3s-install.sh"
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  delegate_to: "{{ item }}"
