---
# tasks file for k3s_cluster

- name: Install k3s on master node
  delegate_to: "{{ groups['k3s_masters'][0] }}"
  block:
    - name: Download k3s install script
      get_url:
        url: "https://get.k3s.io"
        dest: "/tmp/k3s-install.sh"
        mode: '0755'

    - name: Install k3s server
      command: "/tmp/k3s-install.sh --write-kubeconfig-mode 644 --cluster-init"
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        K3S_KUBECONFIG_MODE: "644"

    - name: Get k3s join token
      command: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_join_token
      changed_when: false

- name: Install k3s on worker nodes
  include_tasks: "install_worker.yml"
  with_items: "{{ groups['k3s_workers'] }}"

- name: Retrieve kubeconfig from master
  fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "./kubeconfig"
    flat: yes
  delegate_to: "{{ groups['k3s_masters'][0] }}"
