---
# tasks file for minio

- name: Create minio group
  group:
    name: minio
    state: present

- name: Create minio user
  user:
    name: minio
    group: minio
    home: "{{ minio_data_dir }}"
    create_home: yes
    shell: /bin/bash

- name: Create data directory
  file:
    path: "{{ minio_data_dir }}"
    state: directory
    owner: minio
    group: minio
    mode: '0755'

- name: Download and install minio binary
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio.{{ minio_version }}"
    dest: /usr/local/bin/minio
    mode: '0755'
  notify: restart minio

- name: Create systemd service file
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: Start and enable minio service
  systemd:
    name: minio
    state: started
    enabled: yes
    daemon_reload: yes

- name: Download and install minio exporter binary
  get_url:
    url: "https://github.com/prometheus/minio-exporter/releases/download/v0.0.12/minio-exporter-0.0.12.linux-amd64.tar.gz"
    dest: /tmp/minio-exporter.tar.gz

- name: Unarchive minio exporter
  unarchive:
    src: /tmp/minio-exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move minio exporter binary
  copy:
    src: /tmp/minio-exporter-0.0.12.linux-amd64/minio-exporter
    dest: /usr/local/bin/minio-exporter
    mode: '0755'
    remote_src: yes
  notify: restart minio-exporter

- name: Create systemd service file for minio exporter
  template:
    src: minio-exporter.service.j2
    dest: /etc/systemd/system/minio-exporter.service
  notify: restart minio-exporter

- name: Start and enable minio-exporter service
  systemd:
    name: minio-exporter
    state: started
    enabled: yes
    daemon_reload: yes
