---
# tasks file for minio

- name: Fetch MinIO credentials from Vault
  community.hashi_vault.vault_kv2_get:
    path: "{{ minio_vault_path }}"
  register: minio_credentials

- name: Create minio group
  group:
    name: minio
    state: present

- name: Create minio user
  user:
    name: minio
    group: minio
    home: "{{ minio_data_dir }}"
    create_home: yes
    shell: /bin/bash

- name: Create data directory
  file:
    path: "{{ minio_data_dir }}"
    state: directory
    owner: minio
    group: minio
    mode: '0755'

- name: Download and install minio binary
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio.{{ minio_version }}"
    dest: /usr/local/bin/minio
    mode: '0755'
    checksum: "{{ minio_checksum }}"
  notify: restart minio

- name: Set service credentials
  set_fact:
    service_user: "{{ minio_credentials.data[minio_vault_access_key_name] }}"
    service_password: "{{ minio_credentials.data[minio_vault_secret_key_name] }}"
  no_log: true

- name: Create systemd service file
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: restart minio

- name: Start and enable minio service
  systemd:
    name: minio
    state: started
    enabled: yes
    daemon_reload: yes

- name: Deploy MinIO ServiceMonitor
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'minio-servicemonitor.yml.j2') | from_yaml }}"

- name: Download and install minio exporter binary
  unarchive:
    src: "https://github.com/prometheus/minio-exporter/releases/download/v0.0.12/minio-exporter-0.0.12.linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/minio-exporter
  notify: restart minio-exporter

- name: Create systemd service file for minio exporter
  template:
    src: minio-exporter.service.j2
    dest: /etc/systemd/system/minio-exporter.service
  notify: restart minio-exporter

- name: Start and enable minio-exporter service
  systemd:
    name: minio-exporter
    state: started
    enabled: yes
    daemon_reload: yes
