---
galaxy_info:
  author: "Jules"
  description: "A role to deploy core infrastructure components."
  company: "Homelab"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: "Generic"
      versions:
        - "all"
  galaxy_tags: []
  namespace: "homelab"
  role_name: "core_infra"

dependencies: []
