# Default values for stirling-pdf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: frooodle/s-pdf
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: stirling-pdf.local
      paths:
        - path: /
          pathType: ImplementationSpecific

persistence:
  enabled: false
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: ""
