name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt --check

      - name: TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.1

      - name: TFLint recursive
        run: tflint --recursive


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        working-directory: ./homelab-infra
        run: go test -v ./test/...

  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -r homelab-importer/requirements.txt
          pip install flake8 pytest coverage
      - name: Run flake8
        run: flake8 homelab-importer/
      - name: Run tests with coverage
        run: |
          cd homelab-importer
          coverage run -m unittest discover tests/
          coverage report

  test-synology:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests

      - name: Start mock Synology API server
        run: python ansible/playbooks/mock_synology_api.py &

      - name: Run Synology playbook
        run: ansible-playbook ansible/playbooks/test_synology_mock.yml
