name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt --check

      - name: TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.50.3

      - name: TFLint recursive
        run: tflint --recursive

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
          file_or_dir: ./apps

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Lint Helm charts
        run: helm lint ./charts

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        working-directory: ./infrastructure/proxmox
        run: go test -v ./test/...

  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -r tools/homelab-importer/requirements.txt
          pip install flake8 pytest coverage
      - name: Run flake8
        run: flake8 tools/homelab-importer/
      - name: Run tests with coverage
        run: |
          cd tools/homelab-importer
          coverage run -m unittest discover tests/
          coverage report

  test-synology:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests

      - name: Start mock Synology API server
        run: python ansible/playbooks/mock_synology_api.py &

      - name: Run Synology playbook
        run: ansible-playbook ansible/playbooks/test_synology_mock.yml

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install test dependencies.
        run: pip install ansible-lint
      - name: Run Ansible Lint.
        run: ansible-lint

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          terraform -chdir=infrastructure/proxmox init -backend=false
          terraform -chdir=infrastructure/stealth-vm init -backend=false
      - name: Terraform Validate
        run: |
          terraform -chdir=infrastructure/proxmox validate
          terraform -chdir=infrastructure/stealth-vm validate
