name: Promote to Staging

on:
  workflow_dispatch:

jobs:
  promote-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform workspace select
        run: terraform workspace select staging

      - name: Terraform apply
        run: terraform apply -auto-approve
