name: SBOM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM
        id: sbom
        uses: anchore/sbom-action@v0.17.0
        with:
          path: .
          output-file: "sbom.spdx.json"
          format: "spdx-json"

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
